assets/BGs/bg_hero.svg, assets/BGs/bg_unsere.svg, assets/BGs/map_footer.svg, assets/BGs/qualitat.svg, assets/BGs/under_founders.svg, dist/output.css, index.html, src/components/footer.html, src/pages/founders.html, src/pages/fragen.html, src/pages/hero.html, src/pages/maibornwolff.html, src/pages/managedTeams.html, src/pages/map.html, src/pages/trainingsProgram.html, src/pages/unsere.html, tailwind.config.js
In this pull request we:
- Splitted pages into minicomponents that are rendered into the main index.html
- moved the pages with their backgrounds into components
=> #28: Spliting Pages

.github/pull_request_template.md, dist/output.css
In this pull request I created a template for pull requests
=> chore: Addition of the Pull Request Template

src/components/footer.html, src/components/header.html, src/pages/founders.html, src/pages/fragen.html, src/pages/maibornwolff.html, src/pages/managedTeams.html, src/pages/map.html, src/pages/trainingsProgram.html, src/pages/unsere.html
In this pull request I updated the classes of the sections so that we can work on responsive
The mobile view of the page had big blank space on the right being caused by paddings and margins that are to be applied only on bigger screens
`npm run build`: to build and
`npm run watch`:when you want to add new classes
=> #28: Removing blank spaces to allow responsive design

.gitignore, index.html, src/components/header.html, src/pages/hero.html, tailwind.config.js
In this pull Request I updated the hero section and made it responsive
To make the whole page responsive I had to start with the hero section
`npm run build` : to run with already defined styles
OR
`npm run watch` : If you are in development
**MOBILE VIEW**
**LARGE MOBILE VIEW**
**MINI-TABLET VIEW**
**LARGE TABLET VIEW**
**DESKTOP VIEW**
=> feat:Making Hero section responsive

src/pages/maibornwolff.html
=> Fix:fix zoom out issues on large screen

src/components/header.html, src/pages/hero.html, src/pages/managedTeams.html
In this pull request we included the responsiveness on the Managed Teams section
To make the site visible in all platforms
`npm run build` : If you need only the already defined styles
OR 
`npm run watch` : If you are in development and you will be required to add new styles
** MOBILE**
**TABLET**
**DESTOP**
=> feat:Responsive design for the Managed Teams section

src/pages/fragen.html
=> fix:zoom out issues

.vscode/settings.json, src/pages/founders.html
In this pull Request I fixed the alignment of the founder's section on 2xl screen
This section was being left behind when others are put in center
`npm run build` : If you will use only defined styles
OR
`npm run watch` : If you are in development
=> fix:Fixing alignment on the founder's section on large screen

src/pages/founders.html
In this pull request I removed the blank spaces that were coming on '2xl' breakpoint being caused by the margins that were collecting the alignment and I used the padding Instead
=> fix:Removing the blank space that was caused by the last commit

README.md
ReadMe file for the project
Guiding users to know how they can use our project
-See the screenshot below
=> feat ft/readMe updated README file

src/pages/unsere.html
Fixung Unsere section
To make our sites perfect
clone repo [here](https://github.com/Nezerwa/Ojemba-VLM-Project)
=> bg: bg/unsere

src/input.css
Change in inputcss was causing the fonts not to work so it had to be fixed
The fonts where not working
by checking responsiveness and the css output
=> fix: fixed the input css so we get the right output

src/components/footer.html, src/pages/founders.html, src/pages/hero.html, src/pages/map.html, src/pages/trainingsProgram.html, src/pages/unsere.html
In this pull request I fixed the backgrounds so that they are fit on screen even on bigger screen 
Backgrounds were becoming small on big screen and hiding content
`npm run build` : if you will use defined styles
OR 
`npm run watch` : if you are in development
=> fix:Fixing backgrounds so that on big screens they don't hide content

src/pages/hero.html
Positioned the Ojembees picture they way it is in Figma.
Adhering to the figma style
=> fix: made the ojembees picture fit the figma style

src/components/footer.html
Making the font of the footer roboto and positioning it well.
Adhering to the Figma style and positioning.
=> fix: made the footer font roboto and postioned it well

src/pages/founders.html, src/pages/map.html, tailwind.config.js
In this pull request we worked on the reviews on founders section
=> Fixing founders section

src/pages/founders.html
=> fix:Fixing the founders section

src/pages/founders.html, src/pages/map.html, src/pages/unsere.html, tailwind.config.js
In this PR  I correct typing errors we made while naming colors in tailwind.js file and in pages we used those colors
=> feat: ft/refactor-TypoErrors

src/components/header.html, src/input.css, src/pages/hero.html, src/pages/managedTeams.html, src/pages/trainingsProgram.html
In this pull request we changed all possible vanilla css we could change into tailwind utility classes
=> Transforming vanilla css to tailwindcss as much as possible

src/components/footer.html, src/components/header.html, src/pages/founders.html, src/pages/fragen.html, src/pages/hero.html, src/pages/maibornwolff.html, src/pages/map.html, src/pages/unsere.html
=>  fix: filled the alt attributes and deleted the empty classes

src/components/header.html, src/input.css, src/pages/founders.html, src/pages/hero.html, src/pages/managedTeams.html, src/pages/map.html, src/pages/trainingsProgram.html, src/pages/unsere.html, tailwind.config.js
In this pull request I changed invisible to visible classes to hidden and flex
=> Removing invisible as the style for responsive design

src/components/header.html
In this pull requested I replaced the invisible and visible classes to hidden and flex
=> Replacing invisible and visible with hidden and flex

src/components/footer.html, src/components/header.html, src/pages/founders.html, src/pages/fragen.html, src/pages/hero.html, src/pages/maibornwolff.html, src/pages/managedTeams.html, src/pages/map.html, src/pages/trainingsProgram.html, src/pages/unsere.html, tailwind.config.js
In this pull request I changed the naming convention of the maximum screen into number and change it wherever it is applied and minimized additional breakpoints and named the rest according to the naming format of tailwindcss
=> Screen related Reviews

src/pages/fragen.html
In this PR, I changed color names to Kebaba case from Carmel case and also fix margin on mobile view
=> fix: bg/faqs fixing fonts and margin on fragen section
